name: CI for HKA_timetable_iCal_extender.
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        run: echo "The job was automatically triggered by a ${{ github.event_name }} event." |
          echo "OS ${{ runner.os }}" |
          echo "Branch ${{ github.ref }}, repository ${{ github.repository }}."
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Download Dependencies
        uses: gradle/actions/setup-gradle@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Build and run tests
        run: ./gradlew test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
